# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('notes', models.TextField()),
                ('location', models.CharField(max_length=512)),
                ('meet_date', models.DateTimeField()),
                ('meet_time', models.CharField(max_length=10)),
                ('members', models.ManyToManyField(to='home.Member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='location',
        ),
        migrations.RemoveField(
            model_name='group',
            name='meet_date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='meet_time',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
