# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160625_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='events',
            field=models.ManyToManyField(blank=True, to='home.Event'),
        ),
    ]
