# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_group_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Group'),
            preserve_default=False,
        ),
    ]
